name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-home-cache-cleanup: true
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew clean shadowJar copyGenericJarToBin
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PokeCubed-Installer
        path: |
          build/libs/PokeCubedInstaller-*.jar
          bin/PokeCubedInstaller.jar
        if-no-files-found: warn
        retention-days: 30
        
    - name: Upload to Release
      if: github.event_name == 'release'
      run: |
        # Upload only the generic filename jar from bin
        if [ -f bin/PokeCubedInstaller.jar ]; then
          gh release upload ${{ github.event.release.tag_name }} bin/PokeCubedInstaller.jar
        else
          echo "ERROR: bin/PokeCubedInstaller.jar not found!"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}